
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
markerhub:
  jwt:
    #加密密钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #Token有效时长
    expire: 604800
    header: Authorization

server:
  port: 8081